micronaut:
  application:
    name: demo
  server:
    read-timeout: 30
netty:
  default:
    allocator:
      max-order: 3
s3:
  default:
    folder: mymicronautdemofolder
  bucket:
    name: mymicronautdemobucket2
aws:
  clientId: paste Here AWS ClientId
  clientSecret: paste Here AWS Client Secret


